/**
 * DispatchDisgoAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");

const controller = testerlib.ArtifactsComingSoonController;
const Datum1 = testerlib.Datum1;
const ListDelegatesResponse = testerlib.ListDelegatesResponse;
const Receipt = testerlib.Receipt;
const ListTransactionsResponse = testerlib.ListTransactionsResponse;
const HttpEndpoint = testerlib.HttpEndpoint;
const GrpcEndpoint = testerlib.GrpcEndpoint;
const Datum = testerlib.Datum;


describe("ArtifactsComingSoonController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * Todo Add description for test testAddNewArtifact
     */
    it("should testAddNewArtifact response", function testAddNewArtifactTest(done) {
        controller.addNewArtifact(function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });

    /**
     * Todo Add description for test testListArtifacts
     */
    it("should testListArtifacts response", function testListArtifactsTest(done) {
        controller.listArtifacts(function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });
});
