/**
 * DispatchDisgoAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");

const controller = testerlib.SignTransactionsDevBranchController;
const Datum1 = testerlib.Datum1;
const ListDelegatesResponse = testerlib.ListDelegatesResponse;
const Receipt = testerlib.Receipt;
const ListTransactionsResponse = testerlib.ListTransactionsResponse;
const HttpEndpoint = testerlib.HttpEndpoint;
const GrpcEndpoint = testerlib.GrpcEndpoint;
const Datum = testerlib.Datum;


describe("SignTransactionsDevBranchController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * Todo Add description for test testExecuteSmartContractType2
     */
    it("should testExecuteSmartContractType2 response", function testExecuteSmartContractType2Test(done) {
        // parameters for the API call
        let contentType = 'application/json';

        controller.createExecuteSmartContractType2(contentType, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });

    /**
     * Todo Add description for test testDeploySmartContractType1
     */
    it("should testDeploySmartContractType1 response", function testDeploySmartContractType1Test(done) {
        // parameters for the API call
        let contentType = 'application/json';

        controller.createDeploySmartContractType1(contentType, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });

    /**
     * Todo Add description for test testTokenTransferType0
     */
    it("should testTokenTransferType0 response", function testTokenTransferType0Test(done) {
        // parameters for the API call
        let contentType = 'application/json';

        controller.createTokenTransferType0(contentType, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });
});
