/**
 * DispatchDisgoAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const servers = require('./Servers');
const environments = require('./Environments');
const apiHelper = require('./APIHelper');

const environmentsMap = [];

environmentsMap[environments.PRODUCTION] = [];

environmentsMap[environments.PRODUCTION][servers.SERVER_1] = 'http://seed.dispatchlabs.io:1975/v1';
environmentsMap[environments.PRODUCTION][servers.SERVER_2] = 'http://{ipAddress}:{port}/v1';

const Configuration = {
    /**
     * ipAddress
     * @type {string}
     */
    ipAddress: 'DefaultParameterValue',

    /**
     * port
     * @type {string}
     */
    port: 'DefaultParameterValue',

    /**
     * Current API environment
     * @type {string}
     */
    currentEnvironment: environments.PRODUCTION,

    /**
     * Get base URI for a server in the current API environment
     * @param  {string|null} server Server name
     * @return {string}             Base URI for server
     */
    getBaseUri(server) {
        const url = environmentsMap[this.currentEnvironment][server || servers.SERVER_1];
        const urlParams = {
            ipAddress: this.ipAddress,
            port: this.port,
        };
        return apiHelper.appendUrlWithTemplateParameters(url, urlParams);
    },
};

module.exports = Configuration;
