/**
 * DispatchDisgoAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Datum1 = require('../lib/Models/Datum1');
const ListDelegatesResponse = require('../lib/Models/ListDelegatesResponse');
const Receipt = require('../lib/Models/Receipt');
const ListTransactionsResponse = require('../lib/Models/ListTransactionsResponse');
const HttpEndpoint = require('../lib/Models/HttpEndpoint');
const GrpcEndpoint = require('../lib/Models/GrpcEndpoint');
const Datum = require('../lib/Models/Datum');

const classMap = {
    Datum1,
    ListDelegatesResponse,
    Receipt,
    ListTransactionsResponse,
    HttpEndpoint,
    GrpcEndpoint,
    Datum,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
