/**
 * DispatchDisgoAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Servers = {

    /**
     * TODO: Write general description for this element
     */
    SERVER_1: 'Server 1',

    /**
     * TODO: Write general description for this element
     */
    SERVER_2: 'Server 2',

};

module.exports = Servers;
